name: CI_AutoMerge_Dependabot

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
      - '.github/workflows/prod-func-ci.yml'
      - '.github/workflows/prod-func-deploy.yml'
      - 'docs/*'
    branches:
      - develop

env:
  NODE_VERSION: '14.x'

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Install Dependencies with Npm'
        run: |
          npm i -g npm
          npm set-script prepare ""
          npm install --production

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Build Docker Image'
        run: |
          docker build . -t validator-local:latest

  automerge:
    needs: [build-node, build-docker]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
